//..............................................................................
var utile = require('utile');
var base  = require('../../openstack/storage/container');
//..............................................................................

//..............................................................................
var Container = exports.Container = function Container(client, details)
{
  base.Container.call(this, client, details);
};
utile.inherits(Container, base.Container);
//..............................................................................

